In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_path = 'C:/Users/Melka/Downloads/Telecomunication_data_source.xlsx'
Telecommunication_Industry = pd.read_excel(file_path)

In [18]:
Telecommunication_Industry.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [19]:
#checking for missing values
for col in Telecommunication_Industry.columns:
    missing_values = np.mean(Telecommunication_Industry[col].isnull())
    print('{} - {}%'.format(col, missing_values))

Bearer Id - 0.0%
Start - 6.6666222225185165e-06%
Start ms - 6.6666222225185165e-06%
End - 6.6666222225185165e-06%
End ms - 6.6666222225185165e-06%
Dur. (ms) - 6.6666222225185165e-06%
IMSI - 0.0037999746668355545%
MSISDN/Number - 0.007106619289204739%
IMEI - 0.0038133079112805915%
Last Location Name - 0.007686615422563849%
Avg RTT DL (ms) - 0.1855254298304678%
Avg RTT UL (ms) - 0.18541209725268498%
Avg Bearer TP DL (kbps) - 6.6666222225185165e-06%
Avg Bearer TP UL (kbps) - 6.6666222225185165e-06%
TCP DL Retrans. Vol (Bytes) - 0.5876360824261172%
TCP UL Retrans. Vol (Bytes) - 0.6443223711841921%
DL TP < 50 Kbps (%) - 0.005026633155778962%
50 Kbps < DL TP < 250 Kbps (%) - 0.005026633155778962%
250 Kbps < DL TP < 1 Mbps (%) - 0.005026633155778962%
DL TP > 1 Mbps (%) - 0.005026633155778962%
UL TP < 10 Kbps (%) - 0.005279964800234665%
10 Kbps < UL TP < 50 Kbps (%) - 0.005279964800234665%
50 Kbps < UL TP < 300 Kbps (%) - 0.005279964800234665%
UL TP > 300 Kbps (%) - 0.005279964800234665%
HTTP DL (Bytes) - 0.5431563789574736%
HTTP UL (Bytes) - 0.5453963640242399%
Activity Duration DL (ms) - 6.6666222225185165e-06%
Activity Duration UL (ms) - 6.6666222225185165e-06%
Dur. (ms).1 - 6.6666222225185165e-06%
Handset Manufacturer - 0.0038133079112805915%
Handset Type - 0.0038133079112805915%
Nb of sec with 125000B < Vol DL - 0.650248998340011%
Nb of sec with 1250B < Vol UL < 6250B - 0.619289204738635%
Nb of sec with 31250B < Vol DL < 125000B - 0.6239025073166179%
Nb of sec with 37500B < Vol UL - 0.8683542109719269%
Nb of sec with 6250B < Vol DL < 31250B - 0.5887760748261678%
Nb of sec with 6250B < Vol UL < 37500B - 0.7456150292331385%
Nb of sec with Vol DL < 6250B - 0.00503329977800148%
Nb of sec with Vol UL < 1250B - 0.005286631422457184%
Social Media DL (Bytes) - 0.0%
Social Media UL (Bytes) - 0.0%
Google DL (Bytes) - 0.0%
Google UL (Bytes) - 0.0%
Email DL (Bytes) - 0.0%
Email UL (Bytes) - 0.0%
Youtube DL (Bytes) - 0.0%
Youtube UL (Bytes) - 0.0%
Netflix DL (Bytes) - 0.0%
Netflix UL (Bytes) - 0.0%
Gaming DL (Bytes) - 0.0%
Gaming UL (Bytes) - 0.0%
Other DL (Bytes) - 0.0%
Other UL (Bytes) - 0.0%
Total UL (Bytes) - 6.6666222225185165e-06%
Total DL (Bytes) - 6.6666222225185165e-06%

In [20]:
# Replacing missing values with a zero is a better choice for these columns
Telecommunication_Industry['Start'].fillna(0, inplace=True)
Telecommunication_Industry['End'].fillna(0, inplace=True)
Telecommunication_Industry['Total UL (Bytes)'].fillna(0, inplace=True)
Telecommunication_Industry['Total DL (Bytes)'].fillna(0, inplace=True)
Telecommunication_Industry['Dur. (ms)'].fillna(0, inplace=True)

C:\Users\Melka\AppData\Local\Temp\ipykernel_33280\821185323.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  Telecommunication_Industry['Start'].fillna(0, inplace=True)
C:\Users\Melka\AppData\Local\Temp\ipykernel_33280\821185323.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  Telecommunication_Industry['End'].fillna(0, inplace=True)

In [21]:
#verifying missing values conversion
for col in Telecommunication_Industry.columns:
    missing_values = np.mean(Telecommunication_Industry[col].isnull())
    print('{} - {}%'.format(col, missing_values))

Bearer Id - 0.0%
Start - 0.0%
Start ms - 6.6666222225185165e-06%
End - 0.0%
End ms - 6.6666222225185165e-06%
Dur. (ms) - 0.0%
IMSI - 0.0037999746668355545%
MSISDN/Number - 0.007106619289204739%
IMEI - 0.0038133079112805915%
Last Location Name - 0.007686615422563849%
Avg RTT DL (ms) - 0.1855254298304678%
Avg RTT UL (ms) - 0.18541209725268498%
Avg Bearer TP DL (kbps) - 6.6666222225185165e-06%
Avg Bearer TP UL (kbps) - 6.6666222225185165e-06%
TCP DL Retrans. Vol (Bytes) - 0.5876360824261172%
TCP UL Retrans. Vol (Bytes) - 0.6443223711841921%
DL TP < 50 Kbps (%) - 0.005026633155778962%
50 Kbps < DL TP < 250 Kbps (%) - 0.005026633155778962%
250 Kbps < DL TP < 1 Mbps (%) - 0.005026633155778962%
DL TP > 1 Mbps (%) - 0.005026633155778962%
UL TP < 10 Kbps (%) - 0.005279964800234665%
10 Kbps < UL TP < 50 Kbps (%) - 0.005279964800234665%
50 Kbps < UL TP < 300 Kbps (%) - 0.005279964800234665%
UL TP > 300 Kbps (%) - 0.005279964800234665%
HTTP DL (Bytes) - 0.5431563789574736%
HTTP UL (Bytes) - 0.5453963640242399%
Activity Duration DL (ms) - 6.6666222225185165e-06%
Activity Duration UL (ms) - 6.6666222225185165e-06%
Dur. (ms).1 - 6.6666222225185165e-06%
Handset Manufacturer - 0.0038133079112805915%
Handset Type - 0.0038133079112805915%
Nb of sec with 125000B < Vol DL - 0.650248998340011%
Nb of sec with 1250B < Vol UL < 6250B - 0.619289204738635%
Nb of sec with 31250B < Vol DL < 125000B - 0.6239025073166179%
Nb of sec with 37500B < Vol UL - 0.8683542109719269%
Nb of sec with 6250B < Vol DL < 31250B - 0.5887760748261678%
Nb of sec with 6250B < Vol UL < 37500B - 0.7456150292331385%
Nb of sec with Vol DL < 6250B - 0.00503329977800148%
Nb of sec with Vol UL < 1250B - 0.005286631422457184%
Social Media DL (Bytes) - 0.0%
Social Media UL (Bytes) - 0.0%
Google DL (Bytes) - 0.0%
Google UL (Bytes) - 0.0%
Email DL (Bytes) - 0.0%
Email UL (Bytes) - 0.0%
Youtube DL (Bytes) - 0.0%
Youtube UL (Bytes) - 0.0%
Netflix DL (Bytes) - 0.0%
Netflix UL (Bytes) - 0.0%
Gaming DL (Bytes) - 0.0%
Gaming UL (Bytes) - 0.0%
Other DL (Bytes) - 0.0%
Other UL (Bytes) - 0.0%
Total UL (Bytes) - 0.0%
Total DL (Bytes) - 0.0%

## Calculating duration of the session for each user

In [22]:
Telecommunication_Industry.groupby('MSISDN/Number')['Dur. (ms)'].sum()

MSISDN/Number
3.360100e+10    116720.0
3.360100e+10    181230.0
3.360100e+10    134969.0
3.360101e+10     49878.0
3.360101e+10     37104.0
                  ...
3.379000e+10      8810.0
3.379000e+10    140988.0
3.197021e+12    877385.0
3.370000e+14    253030.0
8.823971e+14    869844.0
Name: Dur. (ms), Length: 106856, dtype: float64

## Calculating total upload and download for each user

In [23]:
DL_and_UL_result = Telecommunication_Industry.groupby('MSISDN/Number').agg({'Total UL (Bytes)': 'sum', 'Total DL (Bytes)': 'sum'})
DL_and_UL_result

               Total UL (Bytes)  Total DL (Bytes)
MSISDN/Number
3.360100e+10         36053108.0      8.426375e+08
3.360100e+10         36104459.0      1.207552e+08
3.360100e+10         39306820.0      5.566597e+08
3.360101e+10         20327526.0      4.019932e+08
3.360101e+10         94280527.0      1.363130e+09
...                         ...               ...
3.379000e+10         26716429.0      6.879252e+08
3.379000e+10         35732243.0      4.445751e+08
3.197021e+12         37295915.0      1.948281e+08
3.370000e+14         56652839.0      5.396350e+08
8.823971e+14         60456049.0      7.869760e+07

[106856 rows x 2 columns]

## Calculating session frequency for each user

In [24]:
Dur_grouped = Telecommunication_Industry.groupby('MSISDN/Number').count()
Dur_grouped
#[Dur_grouped['Start']>5]

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,IMEI,Last Location Name,Avg RTT DL (ms),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
MSISDN/Number,,,,,,,,,,,,,,,,,,,,,
3.360100e+10,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3.360100e+10,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3.360100e+10,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
3.360101e+10,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3.360101e+10,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3.379000e+10,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3.379000e+10,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3.197021e+12,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
3.370000e+14,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
8.823971e+14,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1

## Calculating top 10 users

In [25]:
Telecommunication_Industry['MSISDN/Number'].value_counts().head(10)

MSISDN/Number
3.362632e+10    18
3.361489e+10    17
3.362578e+10    17
3.365973e+10    16
3.376054e+10    15
3.367588e+10    15
3.366716e+10    13
3.360452e+10    12
3.360313e+10    12
3.376041e+10    12
Name: count, dtype: int64

In [26]:
# Creating a new column adding Total DL and Total UL
Telecommunication_Industry['Total_Data_Volume'] = Telecommunication_Industry[['Total UL (Bytes)', 'Total DL (Bytes)']].sum(axis=1)
Telecommunication_Industry.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),Total_Data_Volume
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0,345629377.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0,707185356.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0,307690973.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0,889352748.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0,607681403.0

## Adding download and upload of applications

In [27]:
google = Telecommunication_Industry['Google DL (Bytes)']+ Telecommunication_Industry['Google UL (Bytes)']
email = Telecommunication_Industry['Email DL (Bytes)']+ Telecommunication_Industry['Email UL (Bytes)']
gaming = Telecommunication_Industry['Gaming DL (Bytes)']+ Telecommunication_Industry['Gaming UL (Bytes)']
youtube = Telecommunication_Industry['Youtube DL (Bytes)']+ Telecommunication_Industry['Youtube UL (Bytes)']
netflix = Telecommunication_Industry['Netflix DL (Bytes)']+ Telecommunication_Industry['Netflix UL (Bytes)']
social = Telecommunication_Industry['Social Media DL (Bytes)']+ Telecommunication_Industry['Social Media UL (Bytes)']

Telecommunication_Industry['google']=google
Telecommunication_Industry['email']=email
Telecommunication_Industry['gaming']=gaming
Telecommunication_Industry['youtube']=youtube
Telecommunication_Industry['netflix']=netflix
Telecommunication_Industry['social']=social

In [28]:
Telecommunication_Industry.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),Total_Data_Volume,google,email,gaming,youtube,netflix,social
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,...,8814393.0,36749741.0,308879636.0,345629377.0,2905912.0,3701304.0,292426453.0,18355943.0,17855187.0,1570185.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,15055145.0,53800391.0,653384965.0,707185356.0,4414096.0,937385.0,609920783.0,39359124.0,35565545.0,1933278.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,4215763.0,27883638.0,279807335.0,307690973.0,10229119.0,3363124.0,229980251.0,34425237.0,23751202.0,1726277.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,12797283.0,43324218.0,846028530.0,889352748.0,11811761.0,2070983.0,810387875.0,36534765.0,15092588.0,657493.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,13910322.0,38542814.0,569138589.0,607681403.0,7748843.0,2110349.0,531237049.0,34222253.0,17539799.0,912788.0